# Generated by Django 4.2 on 2025-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='abs/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name_plural': 'Shop by Category',
            },
        ),
    ]
