# Generated by Django 4.2 on 2025-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_contactmessage_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_new',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
