# Generated by Django 4.2 on 2025-03-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ab',
            new_name='Shop_by_Category',
        ),
    ]
