# Generated by Django 4.2 on 2025-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_ab_delete_shop_by_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_by_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='abs/', verbose_name='تصویر')),
            ],
        ),
        migrations.DeleteModel(
            name='ab',
        ),
    ]
