# Generated by Django 4.2 on 2025-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_shop_by_category_delete_ab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_by_category',
            name='image',
            field=models.ImageField(upload_to='Shop_by_Category/', verbose_name='تصویر'),
        ),
    ]
