# Generated by Django 5.0.13 on 2025-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_ab_delete_shop_by_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default_profile.png', upload_to='profile_images/'),
        ),
    ]
