# Generated by Django 5.0.13 on 2025-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_remove_category_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='نام کامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='تلفن'),
            preserve_default=False,
        ),
    ]
