# Generated by Django 5.0.13 on 2025-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_shop_by_category_delete_ab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Shop/', verbose_name='تصویر')),
            ],
        ),
        migrations.DeleteModel(
            name='Shop_by_Category',
        ),
    ]
