# Generated by Django 5.0.13 on 2025-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_ab_delete_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab',
            options={'verbose_name_plural': 'دسته\u200cها'},
        ),
    ]
